-- Replace the previous schema.sql with this complete version.
-- Run in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null default 'New User',
  membership text not null default 'Standard',
  account_status text not null default 'Verified',
  role text not null default 'user' check (role in ('user','admin')),
  member_since date not null default current_date,
  created_at timestamptz not null default now()
);

create table if not exists public.campaigns (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  impressions bigint not null default 0 check (impressions >= 0),
  clicks bigint not null default 0 check (clicks >= 0),
  cpm numeric(12,2) not null default 0 check (cpm >= 0),
  revenue numeric(12,2) not null default 0 check (revenue >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.campaigns enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
on public.profiles for select to authenticated
using (auth.uid() = id or public.is_admin());

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles for update to authenticated
using (auth.uid() = id or public.is_admin())
with check (auth.uid() = id or public.is_admin());

drop policy if exists "Admins can insert profiles" on public.profiles;
create policy "Admins can insert profiles"
on public.profiles for insert to authenticated
with check (public.is_admin());

drop policy if exists "Users can read own campaigns" on public.campaigns;
create policy "Users can read own campaigns"
on public.campaigns for select to authenticated
using (auth.uid() = user_id or public.is_admin());

drop policy if exists "Admins can insert campaigns" on public.campaigns;
create policy "Admins can insert campaigns"
on public.campaigns for insert to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update campaigns" on public.campaigns;
create policy "Admins can update campaigns"
on public.campaigns for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete campaigns" on public.campaigns;
create policy "Admins can delete campaigns"
on public.campaigns for delete to authenticated
using (public.is_admin());

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name, member_since)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', 'New User'),
    current_date
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- IMPORTANT:
-- After creating your own account in Supabase Auth, make that account admin:
--
-- update public.profiles
-- set role = 'admin'
-- where id = 'YOUR_AUTH_USER_UUID';
